log_format  behindproxy  '$http_x_forwarded_for [$time_local] '
                      '"$request_method $request_uri $server_protocol" '
                      '$status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time';

server {
  access_log  /var/log/nginx/access.log behindproxy;

  root /usr/share/nginx/html;

  merge_slashes off;
  rewrite (.*?)//+(.*) $1/$2 redirect;

  include mime.types;
  types {
    font/ttf                ttf;
    application/json        map;
    application/javascript  mjs cjs;
  }

  location ~ \.(css|html|js|mjs|cjs|txt|json|bmp|jpeg|webp|jpg|png|ttf|eot|svg|woff|woff2|map|wasm)$ {
    try_files /$uri =404;
  }

  location / {
    # disable cache
    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since off;
    expires off;
    etag off;

    rewrite ^(.*)$ /index.html break;
  }
}